import type { PreviewComparison } from "./comparison-types";

export const previewComparison: PreviewComparison = {
  metricId: "lifecycle-emissions",
  metricName: "Lifecycle greenhouse-gas emissions",
  metricShortName: "Lifecycle emissions",
  geography: "Global",
  unit: "g CO₂e / kWh",
  defaultComplexity: "curious",
  defaultMode: "typical",
  observations: [
    {
      technologyId: "nuclear",
      technologyName: "Nuclear",
      color: "#a997ff",
      marker: "circle",
      typicalValue: 12,
      range: null,
      evidenceStatus: "unreviewed",
      source: null,
      verifiedAt: null,
    },
    {
      technologyId: "solar",
      technologyName: "Solar",
      color: "#f0b82d",
      marker: "square",
      typicalValue: 40,
      range: null,
      evidenceStatus: "unreviewed",
      source: null,
      verifiedAt: null,
    },
    {
      technologyId: "wind",
      technologyName: "Wind",
      color: "#43c8bf",
      marker: "triangle",
      typicalValue: 11,
      range: null,
      evidenceStatus: "unreviewed",
      source: null,
      verifiedAt: null,
    },
    {
      technologyId: "gas",
      technologyName: "Gas",
      color: "#4d7de8",
      marker: "diamond",
      typicalValue: 490,
      range: null,
      evidenceStatus: "unreviewed",
      source: null,
      verifiedAt: null,
    },
    {
      technologyId: "coal",
      technologyName: "Coal",
      color: "#8c96a3",
      marker: "pentagon",
      typicalValue: 820,
      range: null,
      evidenceStatus: "unreviewed",
      source: null,
      verifiedAt: null,
    },
  ],
};
