import type { ComparisonState, PreviewComparison } from "./comparison-types";

export const mockComparison: PreviewComparison = {
  metricId: "lifecycle-ghg",
  metricName: "Lifecycle greenhouse-gas emissions",
  metricShortName: "Lifecycle emissions",
  geography: "Global",
  unit: "g CO₂e / kWh",
  defaultComplexity: "curious",
  defaultMode: "typical",
  observations: [
    {
      technologyId: "nuclear",
      technologyName: "Nuclear",
      color: "#7B61FF",
      marker: "circle",
      typicalValue: 12,
      range: null,
      evidenceStatus: "reviewed",
      source: null,
      verifiedAt: null,
    },
    {
      technologyId: "solar",
      technologyName: "Solar",
      color: "#FFB020",
      marker: "square",
      typicalValue: 40,
      range: null,
      evidenceStatus: "reviewed",
      source: null,
      verifiedAt: null,
    },
    {
      technologyId: "wind",
      technologyName: "Wind",
      color: "#00CF9D",
      marker: "triangle",
      typicalValue: 11,
      range: null,
      evidenceStatus: "reviewed",
      source: null,
      verifiedAt: null,
    },
    {
      technologyId: "gas",
      technologyName: "Gas",
      color: "#FF5E5E",
      marker: "diamond",
      typicalValue: 490,
      range: null,
      evidenceStatus: "reviewed",
      source: null,
      verifiedAt: null,
    },
    {
      technologyId: "coal",
      technologyName: "Coal",
      color: "#737373",
      marker: "pentagon",
      typicalValue: 820,
      range: null,
      evidenceStatus: "reviewed",
      source: null,
      verifiedAt: null,
    },
  ],
};

export const mockInitialState: ComparisonState = {
  sources: ["nuclear", "solar", "wind", "gas", "coal"],
  metric: "lifecycle-ghg",
  region: "global",
  mode: "typical",
  units: "scientific",
  level: "curious",
};
